services:
  # Backend API Service
  - type: web
    name: kirana-market-api
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        fromService:
          name: kirana-market-frontend
          type: static
          property: url
      - key: ADMIN_URL
        fromService:
          name: kirana-market-frontend
          type: static
          property: url
          envVarKey: ADMIN_URL
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

  # Frontend Static Site
  - type: static
    name: kirana-market-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: kirana-market-api
          type: web
          property: url
          envVarKey: VITE_API_URL
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: ADMIN_URL
        fromService:
          name: kirana-market-frontend
          type: static
          property: url
          suffix: /admin